import { z } from "zod";

/** The four supported explanation/UI languages. */
export const explanationLanguageSchema = z.enum(["de", "en", "dari", "he"]);
export type ExplanationLanguage = z.infer<typeof explanationLanguageSchema>;

/** A single answer option as parsed from a raw paste. */
export const parsedOptionSchema = z.object({
  label: z.string().min(1).max(4), // "A", "B", "C", "D", ...
  text: z.string().min(1),
  isCorrect: z.boolean().nullable(), // null = not determinable from source text
});
export type ParsedOption = z.infer<typeof parsedOptionSchema>;

/**
 * One question as extracted from a large multi-question paste, BEFORE any
 * AI enrichment. The parser must never invent an option or a correct
 * answer — if it can't find one, it leaves the field null/unknown rather
 * than guessing.
 */
export const parsedQuestionSchema = z.object({
  questionNumber: z.string().nullable(),
  questionText: z.string().min(1),
  options: z.array(parsedOptionSchema).min(2),
  correctAnswerUnknown: z.boolean(),
  sourceExplanation: z.string().nullable(),
  category: z.string().nullable(),
  source: z.string().nullable(),
});
export type ParsedQuestion = z.infer<typeof parsedQuestionSchema>;

/**
 * One language's explanation block, generated by the AI enrichment step.
 * Structured (not one blob of prose) so the UI can render "why correct /
 * why wrong / trap" consistently across all four languages.
 */
export const explanationBlockSchema = z.object({
  summary: z.string().min(1),
  whyCorrect: z.string().min(1),
  whyIncorrect: z.string().min(1),
  commonTrap: z.string().nullable(),
  testedConcept: z.string().nullable(),
});
export type ExplanationBlock = z.infer<typeof explanationBlockSchema>;

/** One row of the "Important Words" vocabulary table for a question. */
export const vocabularyItemSchema = z.object({
  germanWord: z.string().min(1),
  englishMeaning: z.string().nullable(),
  dariMeaning: z.string().nullable(),
  hebrewMeaning: z.string().nullable(),
  shortGermanExplanation: z.string().nullable(),
});
export type VocabularyItem = z.infer<typeof vocabularyItemSchema>;

/**
 * Full structured output the AI enrichment step must return for one
 * question. Validated with this schema before anything is written to the
 * database — arbitrary model output is never trusted directly. Only the
 * German explanation is AI-authored (it's the exam's own language); the
 * other three languages are produced by machine-translating this exact
 * text (see batch-enrichment.ts), so all languages always agree.
 */
export const questionEnrichmentSchema = z.object({
  topic: z.string().min(1),
  subtopic: z.string().nullable(),
  difficulty: z.number().int().min(1).max(5),
  examKeywords: z.array(z.string()).max(8),
  explanationDe: explanationBlockSchema,
  vocabulary: z.array(vocabularyItemSchema).max(8),
});
export type QuestionEnrichment = z.infer<typeof questionEnrichmentSchema>;

/** Mistake categories a user's incorrect attempt can be classified under. */
export const mistakeCategorySchema = z.enum(["A", "B", "C", "D", "E", "F"]);
export type MistakeCategory = z.infer<typeof mistakeCategorySchema>;

export const mistakeCategoryLabels: Record<MistakeCategory, string> = {
  A: "Deutsches Sprachverständnis",
  B: "Fachwissen",
  C: "Logik / Schlussfolgerung",
  D: "Flüchtigkeitsfehler",
  E: "Vokabular",
  F: "Unbekannt",
};
