/**
 * Exports every question's existing German content (question stem,
 * explanation, vocabulary) plus its answer options, for a single combined
 * Claude batch that:
 *   1. Re-translates the question stem, explanation, and vocabulary into
 *      SIMPLE, everyday Dari (replacing the more formal/literary Dari
 *      generated by earlier batches) — English/Hebrew are left untouched
 *      since only Dari was reported as too complex.
 *   2. Generates the answer-option translations (en/dari/he) for the first
 *      time, since those were never translated at all for most questions.
 *
 * This intentionally reuses the existing German content as ground truth
 * (never regenerates German, so the underlying explanation reasoning can't
 * drift) and only asks Claude for translation output, not fresh authoring.
 *
 * Usage:
 *   npm run export:dari-improvement -- --email=you@example.com [--batchSize=15] [--out=dir]
 *
 * Writes supabase/seed/dari-improvement/batch-001.json, batch-002.json, …
 * Exports ALL of the user's questions (not just ones missing something),
 * since every question needs at least its Dari re-translated.
 */
import { createClient } from "@supabase/supabase-js";
import { readFileSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

function loadEnvLocal() {
  const path = resolve(process.cwd(), ".env.local");
  if (!existsSync(path)) return;
  for (const line of readFileSync(path, "utf-8").split(/\r?\n/)) {
    const match = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (match && !(match[1] in process.env)) {
      process.env[match[1]] = match[2];
    }
  }
}

function parseArgs() {
  const args = new Map<string, string>();
  for (const arg of process.argv.slice(2)) {
    const match = arg.match(/^--([a-zA-Z]+)=(.*)$/);
    if (match) args.set(match[1], match[2]);
  }
  return args;
}

async function main() {
  loadEnvLocal();
  const args = parseArgs();

  const email = args.get("email") ?? process.env.SEED_USER_EMAIL;
  if (!email) {
    console.error("Usage: npm run export:dari-improvement -- --email=you@example.com [--batchSize=15] [--out=dir]");
    process.exit(1);
  }
  const batchSize = Number(args.get("batchSize") ?? "15") || 15;
  const outDir = resolve(process.cwd(), args.get("out") ?? "supabase/seed/dari-improvement");

  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !serviceRoleKey) {
    console.error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local");
    process.exit(1);
  }

  const supabase = createClient(url, serviceRoleKey, { auth: { autoRefreshToken: false, persistSession: false } });

  let userId: string | null = null;
  for (let page = 1; page <= 20; page++) {
    const { data, error } = await supabase.auth.admin.listUsers({ page, perPage: 200 });
    if (error) throw error;
    const found = data.users.find((u) => u.email?.toLowerCase() === email.toLowerCase());
    if (found) {
      userId = found.id;
      break;
    }
    if (data.users.length < 200) break;
  }
  if (!userId) {
    console.error(`No Supabase auth user found with email ${email}`);
    process.exit(1);
  }

  const { data: questions, error: qError } = await supabase
    .from("questions")
    .select(
      "id, question_text, question_options(id, label, option_text), question_vocabulary(german_word, sort_order)"
    )
    .eq("user_id", userId)
    .order("created_at", { ascending: true });
  if (qError) throw qError;

  const { data: explanations, error: eError } = await supabase
    .from("question_explanations")
    .select("question_id, summary, why_correct, why_incorrect, common_trap, tested_concept")
    .eq("owner_id", userId)
    .eq("language", "de");
  if (eError) throw eError;
  const explanationByQuestion = new Map(explanations?.map((e) => [e.question_id, e]));

  mkdirSync(outDir, { recursive: true });

  const items = (questions ?? []).map((q) => {
    const expl = explanationByQuestion.get(q.id);
    return {
      id: q.id,
      text: q.question_text,
      options: [...q.question_options]
        .sort((a, b) => a.label.localeCompare(b.label))
        .map((o) => ({ label: o.label, text: o.option_text })),
      explanation: expl
        ? {
            summary: expl.summary,
            whyCorrect: expl.why_correct,
            whyIncorrect: expl.why_incorrect,
            commonTrap: expl.common_trap,
            testedConcept: expl.tested_concept,
          }
        : null,
      vocabulary: [...q.question_vocabulary]
        .sort((a, b) => a.sort_order - b.sort_order)
        .map((v) => ({ germanWord: v.german_word })),
    };
  });

  let batchCount = 0;
  for (let i = 0; i < items.length; i += batchSize) {
    batchCount++;
    const batch = items.slice(i, i + batchSize);
    const fileName = `batch-${String(batchCount).padStart(3, "0")}.json`;
    writeFileSync(resolve(outDir, fileName), JSON.stringify(batch, null, 2));
    console.log(`Wrote ${fileName} (${batch.length} question(s))`);
  }

  console.log(
    `\nExported ${items.length} question(s) across ${batchCount} file(s) in ${outDir}.\n` +
      `Paste each batch file into your Claude Project (see scripts/prompts/dari-improvement-prompt.md), ` +
      `send me each reply directly, then once all are collected run:\n` +
      `  npm run import:dari-improvement -- --email=${email}`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
