"use server";

import { getWordTranslation } from "@/lib/translation/translate-word";
import { getQuestionTranslation } from "@/lib/translation/translate-question";
import { getOptionTranslation } from "@/lib/translation/translate-option";
import { createClient } from "@/lib/supabase/server";
import type { ExplanationLanguage } from "@/lib/validation/question";

function resolvePreferredLanguage(rawLang: string | null | undefined): ExplanationLanguage {
  // "de" (the column default) isn't a valid translation target — German is
  // the question's own language — so it falls back to English, same as the
  // Settings radio does.
  return rawLang === "en" || rawLang === "dari" || rawLang === "he" ? rawLang : "en";
}

export async function getWordTranslationAction(word: string) {
  // Any authenticated user can trigger a translation lookup — RLS on
  // `translations` still only allows SELECT for authenticated users; the
  // write happens via the service-role client inside getWordTranslation.
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return null;

  const { data: settings } = await supabase
    .from("user_settings")
    .select("explanation_language")
    .eq("user_id", user.id)
    .maybeSingle();
  const preferredLang = resolvePreferredLanguage(settings?.explanation_language);

  try {
    const translation = await getWordTranslation(word);
    // The `translations` cache always holds every language (it's shared
    // across all users); only the one language matching this user's
    // preference is returned for display.
    return {
      ...translation,
      englishMeaning: preferredLang === "en" ? translation.englishMeaning : null,
      dariMeaning: preferredLang === "dari" ? translation.dariMeaning : null,
      hebrewMeaning: preferredLang === "he" ? translation.hebrewMeaning : null,
    };
  } catch {
    return null;
  }
}

/** Returns a natural, whole-sentence translation of a question's text, if
 * one has already been generated by the offline Claude batch pipeline —
 * `null` otherwise. Never calls an LLM live (see translate-question.ts). */
export async function getQuestionTranslationAction(
  questionId: string
): Promise<{ translation: string; dir: "ltr" | "rtl" } | null> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return null;

  const { data: settings } = await supabase
    .from("user_settings")
    .select("explanation_language")
    .eq("user_id", user.id)
    .maybeSingle();
  const language = resolvePreferredLanguage(settings?.explanation_language);

  try {
    const translation = await getQuestionTranslation(supabase, questionId, language);
    if (!translation) return null;
    return { translation, dir: language === "dari" || language === "he" ? "rtl" : "ltr" };
  } catch (err) {
    console.error("getQuestionTranslationAction failed:", err);
    return null;
  }
}

/** Returns a natural, whole-sentence translation of a single answer option's
 * text, if one has already been generated by the offline Claude batch
 * pipeline — `null` otherwise. Never calls an LLM live (see
 * translate-option.ts). Kept separate from the question's own translation so
 * each option's translation stays paired with that option's German text
 * instead of being bundled into one paragraph. */
export async function getOptionTranslationAction(
  questionOptionId: string
): Promise<{ translation: string; dir: "ltr" | "rtl" } | null> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return null;

  const { data: settings } = await supabase
    .from("user_settings")
    .select("explanation_language")
    .eq("user_id", user.id)
    .maybeSingle();
  const language = resolvePreferredLanguage(settings?.explanation_language);

  try {
    const translation = await getOptionTranslation(supabase, questionOptionId, language);
    if (!translation) return null;
    return { translation, dir: language === "dari" || language === "he" ? "rtl" : "ltr" };
  } catch (err) {
    console.error("getOptionTranslationAction failed:", err);
    return null;
  }
}

export async function logVocabularyViewedAction(questionId: string) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return;
  await supabase
    .from("activity_log")
    .insert({ user_id: user.id, event_type: "translation_viewed", question_id: questionId });
}
